---
title: "Geomorphic Morphometrics on canid skulls"
output: html_notebook
---

```{r setup, include=FALSE, warning=FALSE, message=FALSE}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(echo = TRUE, fig.width = 8.5)
options(knitr.graphics.error = FALSE)

library(ggplot2)
library(patchwork)
library(ggrepel)
# devtools::install_github("lindsaywaldrop/munchcolors")
library(munchcolors)
```


## Running analysis

```{r}
dir.create("./results", showWarnings = F)
dir.create("./results/figures", showWarnings = F)
source("./src/GM_stats.R")
```

## Plotting results


```{r plotting-setup}
# Setting UKC group order
UKC_group_order <- c("NATURAL", "Herding", "Terrier", "Companion", "Gun dog", 
                     "Guardian", "Northern Breed", "Sighthound", "Scenthound")
AKC_group_order <- c("NATURAL", "Herding", "Terrier", "Toy", "Sporting", 
                     "Working", "Non-sporting", "Hound")

# grouping plots ----------------------------------------------------------
# First added your ordered classifiers onto the PCA data
SlicerMorph.repc$UKC <- clsf_reord$UKC.breeding.Standard
SlicerMorph.repc$AKC <- clsf_reord$AKC.breeding.standard
# Set mixed breed to NA for plotting, there is only one!
SlicerMorph.repc$UKC[SlicerMorph.repc$UKC == "MIXED"] <- NA
SlicerMorph.repc$AKC[SlicerMorph.repc$AKC == "MIXED"] <- NA
# Setting fox to natural for AKC/UKC grouping to simplify plots
SlicerMorph.repc$UKC[SlicerMorph.repc$UKC == "FOX"] <- "NATURAL"
SlicerMorph.repc$AKC[SlicerMorph.repc$AKC == "FOX"] <- "NATURAL"

# Changing Yes to lowercase
SlicerMorph.repc$Nosework <- ifelse(clsf_reord$Nose =="Yes" | clsf_reord$Nose == "no", 
                                    tolower(clsf_reord$Nose), clsf_reord$Nose)
# Changing Nosework to ordered factor
SlicerMorph.repc$Nosework <- factor(SlicerMorph.repc$Nosework, ordered = T, 
                                    levels = c("yes", "no", "NATURAL", "FOX"))
# Changing Yes to lowercase 
SlicerMorph.repc$Bitework <- ifelse(clsf_reord$Bitework =="Yes" | clsf_reord$Bitework == "no",
                                    tolower(clsf_reord$Bitework), clsf_reord$Bitework)
# Changing Bitework to ordered factor
SlicerMorph.repc$Bitework <- factor(SlicerMorph.repc$Bitework, ordered = T, 
                                    levels = c("yes", "no", "NATURAL", "FOX"))
# Putting cluster levels into a column as a factor
SlicerMorph.repc$cluster <- factor(km$cluster)

# Now to ease viewing we'll factor them into broad categories

# Turning UKC isnto an ordered factor column
SlicerMorph.repc$UKC.shapefact <- factor(SlicerMorph.repc$UKC, ordered = T, 
                                         levels = UKC_group_order)

## AKC next
SlicerMorph.repc$AKC.shapefact <- factor(SlicerMorph.repc$AKC, 
                                         levels = AKC_group_order)

SlicerMorph.repc$AKC.fact <- factor(SlicerMorph.repc$AKC)

## Setting up a column that is domestic (dogs) and natural (foxes, others)
SlicerMorph.repc$domestic <- factor(ifelse(SlicerMorph.repc$UKC == "NATURAL" | 
                                             SlicerMorph.repc$UKC == "FOX", 
                                           "Natural", "Domesticated"), 
                                    ordered = T, levels = c("Domesticated", "Natural"))

```

K-means clustering plot: 

```{r k-means, echo=FALSE, warning=FALSE, fig.cap="K-means clustering plot."}
#now build the plot
pkmean <- ggplot(SlicerMorph.repc[!is.na(SlicerMorph.repc$UKC),], aes(PC.1, PC.2, color = cluster, 
                                   fill = cluster,
                                   shape = domestic)) + 
  geom_point(size = 2) +
  stat_ellipse(geom = "polygon", aes(fill = cluster, group = cluster), level = 0.95, alpha = 0.1) +
  scale_shape_manual(values = c(5, 19), name = " ") +
  scale_color_munch(choice = "Nietzsche", discrete = TRUE,name = "Cluster") + 
  scale_fill_munch(choice = "Nietzsche", discrete = TRUE, name = "Cluster") +
  geom_text_repel(label = SlicerMorph.repc$Breed[!is.na(SlicerMorph.repc$UKC)], max.overlaps = 4, show.legend = FALSE)+
  xlab("PC 1 (Var = 50.2%)") + ylab("PC 2 (Var = 13.3%)") +
  theme_bw()
pkmean
```

```{r kc-groups, echo=FALSE, warning=FALSE, fig.cap="K-means clustering plot.", fig.height=5.5, fig.width=12}
#now build the plot
kc_palette <- munch_palette("Murderer", 8)
kc_palette <- c(kc_palette, kc_palette[2])
pUKC <- ggplot(SlicerMorph.repc[!is.na(SlicerMorph.repc$UKC),], aes(PC.1, PC.2, color = UKC.shapefact, 
                                   fill = UKC.shapefact,
                                   shape = UKC.shapefact)) + 
  geom_point(size = 2) +
  stat_ellipse(geom = "polygon", aes(group = UKC.shapefact), level = 0.95, alpha = 0.2) +
  scale_shape_manual(values = c(19, 0, 1, 2, 5, 6, 7, 9, 10), name = "UKC Groups") +
  scale_color_manual(values = kc_palette, name = "UKC Groups") + 
  scale_fill_manual(values = kc_palette, name = "UKC Groups") +
  geom_text_repel(label = SlicerMorph.repc$Breed[!is.na(SlicerMorph.repc$UKC)], max.overlaps = 4, show.legend = FALSE)+
  
  xlab("PC 1 (Var = 50.2%)") + ylab("PC 2 (Var = 13.3%)") +
  theme_bw()
pAKC <- ggplot(SlicerMorph.repc[!is.na(SlicerMorph.repc$AKC),], aes(PC.1, PC.2, color = AKC.shapefact, 
                                   fill = AKC.shapefact,
                                   shape = AKC.shapefact)) + 
  geom_point(size = 2) +
  stat_ellipse(geom = "polygon", aes(fill = AKC.shapefact, 
                                     group = AKC.shapefact), level = 0.95, alpha = 0.2) +
  scale_shape_manual(values = c(19, 0, 1, 2, 5, 6, 7, 9, 10), name = "AKC Groups") +
  scale_color_munch(choice = "Murderer", discrete = TRUE, name = "AKC Groups") + 
  scale_fill_munch(choice = "Murderer", discrete = TRUE, name = "AKC Groups") +
  geom_text_repel(label = SlicerMorph.repc$Breed[!is.na(SlicerMorph.repc$AKC)], max.overlaps = 4, show.legend = FALSE)+
  
  xlab("PC 1 (Var = 50.2%)") + ylab("PC 2 (Var = 13.3%)") +
  theme_bw()
pUKC + pAKC
```

```{r fxn-groupings, echo=FALSE, message=FALSE, warning=FALSE, fig.height=3.5, fig.cap="Bitework and scent work."}
fxn_group_palette <- munch_palette("Murderer",8)[c(1:3,5)]
pbite <- ggplot(SlicerMorph.repc, aes(PC.1, PC.2, color = Bitework, 
                                   fill = Bitework,
                                   shape = Bitework)) + 
  geom_point() +
  stat_ellipse(geom = "polygon", level = 0.95, alpha = 0.1) +
  scale_shape_manual(values = c(21, 23, 0, 2), name = " ") +
  scale_color_manual(values = fxn_group_palette, name = " ") + 
  scale_fill_manual(values = fxn_group_palette, name = " ") +
  xlab("PC 1 (Var = 50.2%)") + 
  ylab(" ") +
  ggtitle("Selected for bite work") +
  theme_bw()
pscent <- ggplot(SlicerMorph.repc, aes(PC.1, PC.2, color = Nosework, 
                                   fill = Nosework,
                                   shape = Nosework)) + 
  geom_point() +
  stat_ellipse(geom = "polygon", level = 0.95, alpha = 0.1) +
  scale_shape_manual(values = c(21, 23, 0, 2), name = " ") +
  scale_color_manual(values = fxn_group_palette, name = " ") + 
  scale_fill_manual(values = fxn_group_palette, name = " ") +
  xlab("PC 1 (Var = 50.2%)") + 
  ylab("PC 2 (Var = 13.3%)") +
  ggtitle("Selected for scent work") +
  theme_bw()
pscent + pbite + plot_layout(guides = "collect")

```

```{r bite-force}
bite_data <- data.frame("Breed" = SlicerMorph.repc$Breed, 
                        "Bitework" = SlicerMorph.repc$Bitework, 
                        "Domestic" = SlicerMorph.repc$domestic, 
                        "UKC" = SlicerMorph.repc$UKC, 
                        "AKC" = SlicerMorph.repc$AKC,
                        "canine" = SlicerMorph.repc$bfq_canine, 
                        "carnassial" = SlicerMorph.repc$bfq_carnassial)
bite_data_long <- pivot_longer(bite_data, cols = c("canine","carnassial"))
pforce <- ggplot(bite_data_long, aes(Bitework, value, fill = name)) + 
  geom_boxplot(alpha = 0.6, outlier.shape = NA) + 
  geom_point(alpha = 0.5, position = position_jitterdodge(jitter.width = 0.2), shape = 21) +
  scale_fill_manual(values = munch_palette("YellowLog",2), name = " ") +
  ylab("Bite-force quotient") + xlab("Selected for bite work") +
  theme_bw()
pforce
```

```{r bite-force-stats}
bite_yes_canine <- bite_data$canine[bite_data$Bitework == "yes"]
bite_no_canine <- bite_data$canine[bite_data$Bitework == "no"]
shapiro.test(bite_yes_canine)
shapiro.test(bite_no_canine)
t.test(bite_yes_canine, bite_no_canine)

bite_yes_carnassial <- bite_data$carnassial[bite_data$Bitework == "yes"]
bite_no_carnassial <- bite_data$carnassial[bite_data$Bitework == "no"]
shapiro.test(bite_yes_carnassial)
shapiro.test(bite_no_carnassial)
t.test(bite_yes_carnassial, bite_no_carnassial)

bite_natural_canine <- bite_data$canine[bite_data$Bitework == "NATURAL"]
shapiro.test(bite_natural_canine)
bite_fox_canine <- bite_data$canine[bite_data$Bitework == "FOX"]
shapiro.test(bite_fox_canine)

t.test(bite_yes_canine, bite_natural_canine)
t.test(bite_yes_canine, bite_fox_canine)
```


## For the paper: 

Figure 2: 

```{r fig-2, echo=FALSE, warning=FALSE, fig.cap="A. K-means clustering plot. B. AKC groupings. C. UKC groupings.", fig.height=7.5, fig.width=12}
pkmean / (pAKC + pUKC) + plot_annotation(tag_levels = "A")
ggsave("./results/figures/figure2.pdf")
```

Figure 3: 

```{r fig-3, echo=FALSE, warning=FALSE, fig.cap="K-means clustering plot.", fig.height=7.5, fig.width=10}
(pscent + pbite + plot_layout(guides = "collect")) / pforce  + plot_annotation(tag_levels = "A")
ggsave("./results/figures/figure3.pdf")
```
